### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by excelliumCoin** [dominant-strategies/hardhat-example#29]
Info: SolidityX Path not specified. Using default path: /workspaces/codespaces-blank/hardhat-example/solc
Info: SolidityX Path not specified. Using default path: /workspaces/codespaces-blank/hardhat-example/solc
TypeError: Cannot read properties of null (reading 'fromRed')
    at Point.getX (/workspaces/codespaces-blank/hardhat-example/node_modules/elliptic/lib/elliptic/curve/short.js:415:17)
    at Point._encode (/workspaces/codespaces-blank/hardhat-example/node_modules/elliptic/lib/elliptic/curve/base.js:300:16)
    at Point.encode (/workspaces/codespaces-blank/hardhat-example/node_modules/elliptic/lib/elliptic/curve/base.js:309:28)
    at KeyPair.getPublic (/workspaces/codespaces-blank/hardhat-example/node_modules/elliptic/lib/elliptic/ec/key.js:66:19)
    at new SigningKey (/workspaces/codespaces-blank/hardhat-example/node_modules/@quais/signing-key/src.ts/index.ts:42:58)
    at new Wallet (/workspaces/codespaces-blank/hardhat-example/node_modules/@quais/wallet/src.ts/index.ts:87:36)
    at main (/workspaces/codespaces-blank/hardhat-example/scripts/deploy.js:16:29)
    at Object.<anonymous> (/workspaces/codespaces-blank/hardhat-example/scripts/deploy.js:38:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by Juuddi** [comment]
What version of `quai-hardhat-plugin` are you using? This should have been fixed with the most recent version (1.0.2)

**Comment by Juuddi** [comment]
Closing this as it has been fixed by the latest version of `quai-hardhat-plugin`
